name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
          
    - name: Download JBR 17
      run: |
        download_url="https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-17.0.7-linux-x64-b964.1.tar.gz"
        wget -O $RUNNER_TEMP/jbr.tar.gz $download_url
        
    - name: Setup JBR 17
      uses: actions/setup-java@v3
      with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/jbr.tar.gz
          java-version: '17'
          architecture: x64
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Setup signing key
      if: github.ref == 'refs/heads/main'
      run: |
        if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
          echo keyStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> local.properties
          echo keyAlias='${{ secrets.KEY_ALIAS }}' >> local.properties
          echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> local.properties
          echo keyStore='${{ github.workspace }}/key.jks' >> local.properties
          echo ${{ secrets.KEY_STORE }} | base64 --decode > ${{ github.workspace }}/key.jks
        fi

    - name: Build with Gradle
      run: ./gradlew assembleRelease
    
    - name: Upload built apk
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: Apk
        path: ${{ github.workspace }}/app/build/outputs/apk/release/*.apk
